interface INames {
    [key: string]: string;
}

export const names: INames = {
    'Legs': 'Штаны',
    'Masks': 'Маска',
    'trash': 'Мусор',
    'water': 'Вода',
    'sandwich': 'Сэндвич',
    'phone': 'Телефон',
    'firstAidKit': 'Аптечка',
    'cigarettes': 'Сигареты',
    'weed': 'Трава',  
    'rod': 'Удочка',
    'fish': 'Рыба',
    'bonfire': 'Костер',
    'wetsuit': 'Гидрокостюм',
    'BagsAndParachutes': 'Сумка',
    'Parachutes': 'Парашют',
    'Shoes': 'Кеды',
    'Accessories': 'Аксессуары',
    'BodyArmors': 'Броня',
    'Hats': 'Шляпа',
    'Glasses': 'Очки',
    'Gloves': 'Перчатки',
    'Ears': 'Ears',
    'Watches': 'Часы',
    'Bracelets': 'браслет',
    'map': 'Карта рыболова',
    'anesthesia': 'Наркоз',
    'painReliever': 'Обезболивающее',
    'epinephrine': 'Эпинефрин',
    'santa': 'Костюм Санты',
    'tron': 'Костюм Трон',
    'neon': 'Костюм Неон',
    'meth' : 'Метамфетамин',
    'heroin' : 'Героин',
    'lighter' : 'Зажигалка',
    'spruce' : 'Елка',
    'tako' : 'Тако',
    'adrenalin' : 'Адреналин',
    'masterKey' : 'Отмычка',
    'coupon' : 'Автокупон',
    'radio': 'Рация',
    'bag': 'Сумка'
}